Repository arfc/2019-09-05-group, pull requests merged in 2019-09, with the labels that each got.

#10 gwen slides
  2019-09-05-group.bib
  arfc-pres.tex
  chee.tex
  images/d3ploy-flow.png
Labels: Type:Docs

#14 Issue1 - adds Ansh's slides
  chaube.tex
  images/conv_nuc_elc.png
  images/msre-flat.png
Labels: Comp:Core, Difficulty:1-Beginner, Priority:1-Critical, Status:1-New, Type:Docs

#15 Adding Pyre Slides
  cyclus.tex
  images/diversion1.png
  images/lanl-fuel-cycle.png
  images/westphal-diversion.PNG
  images/westphal-pyre.pdf
  westphal.tex
Labels: Difficulty:1-Beginner, Priority:2-Normal, Type:Docs
